version: "3.9"
services:
  laravel:
    image: laravelsail/php83-composer
    container_name: laravel
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    networks: [appnet]

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks: [appnet]

  grafana:
    image: grafana/grafana:12.1.0
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks: [appnet]

networks:
  appnet:

volumes:
  dbdata:
  grafana_data:
